---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
#  storageClassName: standard
#  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/pv-spin/minio"
  claimRef:
    kind: PersistentVolumeClaim
    name: spin-minio
    namespace: offline

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
# storageClassName: standard
#  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/pv-spin/redis"
  claimRef:
    kind: PersistentVolumeClaim
    name: redis-data-spin-redis-master-0
    namespace: offline
  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-halyard
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
#  storageClassName: standard
#  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/pv-spin/halyard"
  claimRef:
    kind: PersistentVolumeClaim
    name: halyard-home-spin-spinnaker-halyard-0
    namespace: offline
 
